import type { FindingTriageVerdict } from "./finding-triage";

export interface AuditorReviewCase {
	id: string;
	title: string;
	detector: string;
	severity: "critical" | "high" | "medium" | "low" | "info";
	expectedBucket: "report_finding" | "needs_review" | "research_note";
	expectedVerdict: FindingTriageVerdict;
	shouldHeadline: boolean;
	why: string;
	tags: string[];
	finding: Record<string, unknown>;
}

export const TRIAGE_AUDITOR_REVIEWSET: AuditorReviewCase[] = [
	{
		id: "headline-liquidation-before-accounting",
		title: "Public liquidation pays attacker-chosen recipient before debt state is cleared",
		detector: "arbitrary-send-eth",
		severity: "high",
		expectedBucket: "report_finding",
		expectedVerdict: "likely_real",
		shouldHeadline: true,
		why: "Public reachability, attacker-chosen payout routing, and economically sensitive state finalized after transfer make this a defensible headline finding.",
		tags: ["headline", "funds-loss", "effects-after-interaction"],
		finding: {
			id: "headline-liquidation-before-accounting",
			severity: "high",
			findingState: "raw_lead",
			originalId: "arbitrary-send-eth",
			isExternal: false,
			semanticFacts: {
				functionName: "liquidate",
				contractName: "BorrowProtocol",
				inheritanceParents: [],
				overrideContext: [],
				visibility: "external",
				modifiers: [],
				auth: [],
				externalCalls: ['payable(recipient).call{value: loan.collateralAmount}("")'],
				stateWritesBeforeCalls: [],
				stateWritesAfterCalls: ["delete loans[user][loanId];"],
				affectedStateSlots: ["loans[user][loanId]"],
				valueSourceExpressions: ["loan.collateralAmount"],
				stateFinalizedBeforeExternalCall: false,
				postCallStateDependsOnSuccess: true,
				attackerControlledArgs: ["recipient", "user", "loanId"],
				provenanceSources: {
					recipientSource: "user_arg",
					amountSource: "storage_lookup",
					targetSource: "unknown",
				},
				arithmeticControlledArgs: [],
				trustBoundary: "public_or_unrestricted",
				isDependency: false,
			},
		},
	},
	{
		id: "headline-tx-origin-withdrawal",
		title: "Withdrawal relies on tx.origin authorization",
		detector: "tx-origin",
		severity: "high",
		expectedBucket: "report_finding",
		expectedVerdict: "likely_real",
		shouldHeadline: true,
		why: "A public withdrawal path protected by tx.origin is a classic, auditor-defensible auth bug.",
		tags: ["headline", "auth", "phishing"],
		finding: {
			id: "headline-tx-origin-withdrawal",
			severity: "high",
			findingState: "raw_lead",
			originalId: "tx-origin",
			isExternal: false,
			semanticFacts: {
				functionName: "withdraw",
				contractName: "Treasury",
				inheritanceParents: [],
				overrideContext: [],
				visibility: "external",
				modifiers: [],
				auth: [],
				externalCalls: ['to.call{value: amount}("")'],
				stateWritesBeforeCalls: [],
				stateWritesAfterCalls: [],
				affectedStateSlots: [],
				valueSourceExpressions: ["amount"],
				stateFinalizedBeforeExternalCall: true,
				postCallStateDependsOnSuccess: false,
				attackerControlledArgs: ["to", "amount"],
				provenanceSources: {
					recipientSource: "user_arg",
					amountSource: "user_arg",
					targetSource: "unknown",
				},
				arithmeticControlledArgs: [],
				trustBoundary: "public_or_unrestricted",
				isDependency: false,
			},
		},
	},
	{
		id: "non-headline-public-upgrade-entry",
		title: "Public upgrade entrypoint without visible auth",
		detector: "unprotected-upgrade",
		severity: "high",
		expectedBucket: "needs_review",
		expectedVerdict: "likely_real",
		shouldHeadline: false,
		why: "Risk is strong, but without full proxy wiring and inherited context this should stay out of the main report.",
		tags: ["non-headline", "upgradeability", "context-dependent"],
		finding: {
			id: "non-headline-public-upgrade-entry",
			severity: "high",
			findingState: "raw_lead",
			originalId: "unprotected-upgrade",
			isExternal: false,
			semanticFacts: {
				functionName: "upgradeTo",
				contractName: "VaultProxy",
				inheritanceParents: [],
				overrideContext: [],
				visibility: "external",
				modifiers: [],
				auth: [],
				externalCalls: [],
				stateWritesBeforeCalls: [],
				stateWritesAfterCalls: [],
				affectedStateSlots: ["implementation"],
				valueSourceExpressions: [],
				stateFinalizedBeforeExternalCall: true,
				postCallStateDependsOnSuccess: false,
				attackerControlledArgs: ["newImplementation"],
				provenanceSources: {
					recipientSource: "unknown",
					amountSource: "unknown",
					targetSource: "user_arg",
				},
				arithmeticControlledArgs: [],
				trustBoundary: "public_or_unrestricted",
				isDependency: false,
			},
		},
	},
	{
		id: "non-headline-signer-payout",
		title: "Signer-authorized payout routing",
		detector: "arbitrary-send-eth",
		severity: "high",
		expectedBucket: "research_note",
		expectedVerdict: "likely_real",
		shouldHeadline: false,
		why: "Dangerous-looking sink, but signer-constrained business logic should not become a headline finding without a stronger signer-bypass story.",
		tags: ["non-headline", "signer-flow", "business-logic"],
		finding: {
			id: "non-headline-signer-payout",
			severity: "high",
			findingState: "raw_lead",
			originalId: "arbitrary-send-eth",
			isExternal: false,
			semanticFacts: {
				functionName: "processPayout",
				contractName: "Rewards",
				inheritanceParents: [],
				overrideContext: [],
				visibility: "external",
				modifiers: [],
				auth: ["signature_validation"],
				externalCalls: ['payable(data.recipient).call{value: data.amount}("")'],
				stateWritesBeforeCalls: [],
				stateWritesAfterCalls: [],
				affectedStateSlots: [],
				valueSourceExpressions: ["data.amount"],
				stateFinalizedBeforeExternalCall: true,
				postCallStateDependsOnSuccess: false,
				attackerControlledArgs: [],
				provenanceSources: {
					recipientSource: "signer_payload",
					amountSource: "signer_payload",
					targetSource: "unknown",
				},
				arithmeticControlledArgs: [],
				trustBoundary: "signature_authorized",
				isDependency: false,
			},
		},
	},
	{
		id: "non-headline-finalized-withdrawal",
		title: "Withdrawal with state finalized before external call",
		detector: "reentrancy-benign",
		severity: "low",
		expectedBucket: "research_note",
		expectedVerdict: "needs_human_review",
		shouldHeadline: false,
		why: "Even if the detector fires, a clearly finalized state transition before the call is not something we should headline.",
		tags: ["non-headline", "reentrancy", "finalized-state"],
		finding: {
			id: "non-headline-finalized-withdrawal",
			severity: "low",
			findingState: "raw_lead",
			originalId: "reentrancy-benign",
			isExternal: false,
			semanticFacts: {
				functionName: "withdraw",
				contractName: "Vault",
				inheritanceParents: [],
				overrideContext: [],
				visibility: "external",
				modifiers: [],
				auth: [],
				externalCalls: ['payable(msg.sender).call{value: amount}("")'],
				stateWritesBeforeCalls: ["balances[msg.sender] = 0;"],
				stateWritesAfterCalls: [],
				affectedStateSlots: ["balances[msg.sender]"],
				valueSourceExpressions: ["balances[msg.sender]"],
				stateFinalizedBeforeExternalCall: true,
				postCallStateDependsOnSuccess: false,
				attackerControlledArgs: [],
				provenanceSources: {
					recipientSource: "msg_sender",
					amountSource: "storage_lookup",
					targetSource: "unknown",
				},
				arithmeticControlledArgs: [],
				trustBoundary: "public_or_unrestricted",
				isDependency: false,
			},
		},
	},
	{
		id: "non-headline-public-lowlevel-target",
		title: "Public low-level call to attacker-chosen target",
		detector: "low-level-calls",
		severity: "medium",
		expectedBucket: "needs_review",
		expectedVerdict: "likely_real",
		shouldHeadline: false,
		why: "Attacker-chosen low-level calls are risky, but without stronger value-flow or control-flow impact proof this should remain a manual-review item.",
		tags: ["non-headline", "low-level-call", "target-control"],
		finding: {
			id: "non-headline-public-lowlevel-target",
			severity: "medium",
			findingState: "raw_lead",
			originalId: "low-level-calls",
			isExternal: false,
			semanticFacts: {
				functionName: "execute",
				contractName: "Executor",
				inheritanceParents: [],
				overrideContext: [],
				visibility: "external",
				modifiers: [],
				auth: [],
				externalCalls: ["target.call(data)"],
				stateWritesBeforeCalls: [],
				stateWritesAfterCalls: [],
				affectedStateSlots: [],
				valueSourceExpressions: [],
				stateFinalizedBeforeExternalCall: true,
				postCallStateDependsOnSuccess: false,
				attackerControlledArgs: ["target", "data"],
				provenanceSources: {
					recipientSource: "unknown",
					amountSource: "unknown",
					targetSource: "user_arg",
				},
				arithmeticControlledArgs: [],
				trustBoundary: "public_or_unrestricted",
				isDependency: false,
			},
		},
	},
	{
		id: "non-headline-role-gated-lowlevel-target",
		title: "Role-gated low-level execution helper",
		detector: "unchecked-lowlevel",
		severity: "medium",
		expectedBucket: "research_note",
		expectedVerdict: "likely_real",
		shouldHeadline: false,
		why: "A privileged low-level helper may still deserve engineering review, but it should not appear as a headline protocol vuln by default.",
		tags: ["non-headline", "low-level-call", "privileged-flow"],
		finding: {
			id: "non-headline-role-gated-lowlevel-target",
			severity: "medium",
			findingState: "raw_lead",
			originalId: "unchecked-lowlevel",
			isExternal: false,
			semanticFacts: {
				functionName: "adminExecute",
				contractName: "Executor",
				inheritanceParents: [],
				overrideContext: [],
				visibility: "external",
				modifiers: ["onlyRole(EXECUTOR_ROLE)"],
				auth: ["role_gated"],
				externalCalls: ["target.call(data)"],
				stateWritesBeforeCalls: [],
				stateWritesAfterCalls: [],
				affectedStateSlots: [],
				valueSourceExpressions: [],
				stateFinalizedBeforeExternalCall: true,
				postCallStateDependsOnSuccess: false,
				attackerControlledArgs: [],
				provenanceSources: {
					recipientSource: "unknown",
					amountSource: "unknown",
					targetSource: "storage",
				},
				arithmeticControlledArgs: [],
				trustBoundary: "role_gated",
				isDependency: false,
			},
		},
	},
	{
		id: "non-headline-zero-address-config",
		title: "Public setter accepts zero treasury address",
		detector: "missing-zero-check",
		severity: "low",
		expectedBucket: "needs_review",
		expectedVerdict: "likely_real",
		shouldHeadline: false,
		why: "A public zero-address configuration bug can matter, but it is usually a context-heavy review item rather than a headline exploit by itself.",
		tags: ["non-headline", "input-validation", "config-risk"],
		finding: {
			id: "non-headline-zero-address-config",
			severity: "low",
			findingState: "raw_lead",
			originalId: "missing-zero-check",
			isExternal: false,
			semanticFacts: {
				functionName: "setTreasury",
				contractName: "VaultConfig",
				inheritanceParents: [],
				overrideContext: [],
				visibility: "external",
				modifiers: [],
				auth: [],
				externalCalls: [],
				stateWritesBeforeCalls: ["treasury = newTreasury;"],
				stateWritesAfterCalls: [],
				affectedStateSlots: ["treasury"],
				valueSourceExpressions: [],
				stateFinalizedBeforeExternalCall: true,
				postCallStateDependsOnSuccess: false,
				attackerControlledArgs: ["newTreasury"],
				provenanceSources: {
					recipientSource: "user_arg",
					amountSource: "unknown",
					targetSource: "unknown",
				},
				arithmeticControlledArgs: [],
				trustBoundary: "public_or_unrestricted",
				isDependency: false,
			},
		},
	},
	{
		id: "non-headline-owner-zero-address-config",
		title: "Owner-only treasury setter without zero-address check",
		detector: "missing-zero-check",
		severity: "low",
		expectedBucket: "research_note",
		expectedVerdict: "likely_real",
		shouldHeadline: false,
		why: "Privileged configuration mistakes should be visible for review, but not escalated into main-report vulns by default.",
		tags: ["non-headline", "input-validation", "privileged-config"],
		finding: {
			id: "non-headline-owner-zero-address-config",
			severity: "low",
			findingState: "raw_lead",
			originalId: "missing-zero-check",
			isExternal: false,
			semanticFacts: {
				functionName: "setTreasury",
				contractName: "VaultConfig",
				inheritanceParents: [],
				overrideContext: [],
				visibility: "external",
				modifiers: ["onlyOwner"],
				auth: ["owner_only"],
				externalCalls: [],
				stateWritesBeforeCalls: ["treasury = newTreasury;"],
				stateWritesAfterCalls: [],
				affectedStateSlots: ["treasury"],
				valueSourceExpressions: [],
				stateFinalizedBeforeExternalCall: true,
				postCallStateDependsOnSuccess: false,
				attackerControlledArgs: ["newTreasury"],
				provenanceSources: {
					recipientSource: "user_arg",
					amountSource: "unknown",
					targetSource: "unknown",
				},
				arithmeticControlledArgs: [],
				trustBoundary: "owner_only",
				isDependency: false,
			},
		},
	},
	{
		id: "non-headline-public-precision-bug",
		title: "Public quote path uses user-controlled divide-before-multiply math",
		detector: "divide-before-multiply",
		severity: "medium",
		expectedBucket: "needs_review",
		expectedVerdict: "likely_real",
		shouldHeadline: false,
		why: "Economic precision issues deserve real attention, but without a stronger exploit consequence they should remain review candidates rather than headline bugs.",
		tags: ["non-headline", "accounting", "precision"],
		finding: {
			id: "non-headline-public-precision-bug",
			severity: "medium",
			findingState: "raw_lead",
			originalId: "divide-before-multiply",
			isExternal: false,
			semanticFacts: {
				functionName: "quote",
				contractName: "VaultMath",
				inheritanceParents: [],
				overrideContext: [],
				visibility: "external",
				modifiers: [],
				auth: [],
				externalCalls: [],
				stateWritesBeforeCalls: [],
				stateWritesAfterCalls: [],
				affectedStateSlots: [],
				valueSourceExpressions: [],
				stateFinalizedBeforeExternalCall: true,
				postCallStateDependsOnSuccess: false,
				attackerControlledArgs: [],
				provenanceSources: {
					recipientSource: "unknown",
					amountSource: "unknown",
					targetSource: "unknown",
				},
				arithmeticControlledArgs: ["assets", "supply", "feeBps"],
				trustBoundary: "public_or_unrestricted",
				isDependency: false,
			},
		},
	},
	{
		id: "non-headline-owner-precision-helper",
		title: "Internal precision helper flagged by static analysis",
		detector: "incorrect-exp",
		severity: "medium",
		expectedBucket: "research_note",
		expectedVerdict: "likely_real",
		shouldHeadline: false,
		why: "Non-user-reachable math helpers should stay suppressed unless we can tie them to a real exploit path.",
		tags: ["non-headline", "accounting", "internal-helper"],
		finding: {
			id: "non-headline-owner-precision-helper",
			severity: "medium",
			findingState: "raw_lead",
			originalId: "incorrect-exp",
			isExternal: false,
			semanticFacts: {
				functionName: "_scaleExponent",
				contractName: "VaultMath",
				inheritanceParents: [],
				overrideContext: [],
				visibility: "internal",
				modifiers: [],
				auth: [],
				externalCalls: [],
				stateWritesBeforeCalls: [],
				stateWritesAfterCalls: [],
				affectedStateSlots: [],
				valueSourceExpressions: [],
				stateFinalizedBeforeExternalCall: true,
				postCallStateDependsOnSuccess: false,
				attackerControlledArgs: [],
				provenanceSources: {
					recipientSource: "unknown",
					amountSource: "unknown",
					targetSource: "unknown",
				},
				arithmeticControlledArgs: [],
				trustBoundary: "internal_only",
				isDependency: false,
			},
		},
	},
];
